// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';

// Configuration Supabase avec variables d'environnement
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Log for debugging deployment issue: configuration Supabase
logger.info('supabase/client', 'Initializing Supabase client', {
  hasUrl: Boolean(SUPABASE_URL),
  hasAnonKey: Boolean(SUPABASE_PUBLISHABLE_KEY),
});

// Vérification des variables d'environnement requises
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  logger.error('supabase/client', 'Missing Supabase env vars', { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY ? 'present' : 'missing' });
  throw new Error(
    'Variables d\'environnement Supabase manquantes. Veuillez vérifier VITE_SUPABASE_URL et VITE_SUPABASE_ANON_KEY.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

logger.info('supabase/client', 'Supabase client created successfully');